seed: 42
gpu: 0
save_dir: runs
save_name: ~
overwrite: false
resume: ~

model:
  dino2: dinov2_vitl14
  image_size: 224
  electra: dbmdz/electra-base-turkish-mc4-cased-discriminator
  max_length: 35
  projection_adapter: cross_attention   # P4 -- Cross-Attention (single layer, no Q-Former)
  projection_adapter_kwargs:
    num_queries: 32
    num_heads: 8
  freeze_encoder: true
  train_decoder: true
  train_projection: true

lr_decoder: 1e-5
lr_projection: 5e-5
betas: [0.9, 0.99]
weight_decay: 0.01

num_workers: 8
batch_size: 64
max_iter: 12000
warm_up_iter: 500
num_eval_iter: 1000
target_metric: 'CIDEr'

train_dataset_root: Data/flickr8k/images
train_json_path: Data/tasvir-et/tasvir_train.json

test_dataset_root: Data/flickr8k/images
val_json_path: Data/tasvir-et/tasvir_val.json
